// <auto-generated />
using System;
using Emit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Emit.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603132345_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Emit.Api.Entities.Cours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FiliereId")
                        .HasColumnType("uuid");

                    b.Property<int>("HeuresPlanifiees")
                        .HasColumnType("integer");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FiliereId");

                    b.HasIndex("NiveauId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("Emit.Api.Entities.CoursEnseignant", b =>
                {
                    b.Property<Guid>("CoursId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnseignantId")
                        .HasColumnType("uuid");

                    b.HasKey("CoursId", "EnseignantId");

                    b.HasIndex("EnseignantId");

                    b.ToTable("CoursEnseignants");
                });

            modelBuilder.Entity("Emit.Api.Entities.Enseignant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("Emit.Api.Entities.Filiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NiveauId");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("Emit.Api.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Ancien")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nouveau")
                        .HasColumnType("text");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("Emit.Api.Entities.Niveau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EffectifMax")
                        .HasColumnType("integer");

                    b.Property<int>("Libelle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("Emit.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Emit.Api.Entities.Salle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Batiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Occupation")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("Emit.Api.Entities.Semestre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Annee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DatePublication")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Semestres");
                });

            modelBuilder.Entity("Emit.Api.Entities.SlotEDT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoursId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnseignantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FiliereId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemestreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("FiliereId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("SalleId");

                    b.HasIndex("SemestreId", "Jour", "HeureDebut", "EnseignantId")
                        .IsUnique();

                    b.HasIndex("SemestreId", "Jour", "HeureDebut", "SalleId")
                        .IsUnique();

                    b.HasIndex("SemestreId", "Jour", "HeureDebut", "NiveauId", "FiliereId")
                        .IsUnique();

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Emit.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EnseignantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EnseignantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Emit.Api.Entities.Cours", b =>
                {
                    b.HasOne("Emit.Api.Entities.Filiere", "Filiere")
                        .WithMany("Cours")
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Niveau", "Niveau")
                        .WithMany("Cours")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filiere");

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("Emit.Api.Entities.CoursEnseignant", b =>
                {
                    b.HasOne("Emit.Api.Entities.Cours", "Cours")
                        .WithMany("Enseignants")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Enseignant", "Enseignant")
                        .WithMany("Cours")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("Emit.Api.Entities.Filiere", b =>
                {
                    b.HasOne("Emit.Api.Entities.Niveau", "Niveau")
                        .WithMany("Filieres")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("Emit.Api.Entities.Notification", b =>
                {
                    b.HasOne("Emit.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emit.Api.Entities.SlotEDT", b =>
                {
                    b.HasOne("Emit.Api.Entities.Cours", "Cours")
                        .WithMany("Slots")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Enseignant", "Enseignant")
                        .WithMany("Slots")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Filiere", "Filiere")
                        .WithMany()
                        .HasForeignKey("FiliereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Salle", "Salle")
                        .WithMany("Slots")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emit.Api.Entities.Semestre", "Semestre")
                        .WithMany("Slots")
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Enseignant");

                    b.Navigation("Filiere");

                    b.Navigation("Niveau");

                    b.Navigation("Salle");

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("Emit.Api.Entities.User", b =>
                {
                    b.HasOne("Emit.Api.Entities.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("Emit.Api.Entities.Cours", b =>
                {
                    b.Navigation("Enseignants");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Emit.Api.Entities.Enseignant", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Emit.Api.Entities.Filiere", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Emit.Api.Entities.Niveau", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Filieres");
                });

            modelBuilder.Entity("Emit.Api.Entities.Salle", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Emit.Api.Entities.Semestre", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
